package:
  name: q2-amrfinderplus
  version: {{ version }}

source:
  path: ..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - ncbi-amrfinderplus
    - python {{ python }}
    - qiime2 {{ qiime2_epoch }}.*
    - q2-feature-table {{ qiime2_epoch }}.*
    - q2-metadata {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2cli {{ qiime2_epoch }}.*

test:
  requires:
    - coverage
    - pytest-cov
  imports:
    - q2_amrfinderplus
    - qiime2.plugins.amrfinderplus
  commands:
    - pytest --cov q2_amrfinderplus --cov-report xml:coverage.xml --pyargs q2_amrfinderplus

about:
  home: https://github.com/bokulich-lab/q2-q2_amrfinderplus
  license: BSD-3-Clause
  license_family: BSD
