package:
  name: q2-amrfinderplus
  version: {{ PLUGIN_VERSION }}

source:
  path: ..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools
    - versioningit
    - wheel

  build:
    - python {{ python }}
    - setuptools
    - versioningit

  run:
    - ncbi-amrfinderplus >={{ ncbi_amrfinderplus }}
    - qiime2 >={{ qiime2 }}
    - q2-metadata >={{ q2_metadata }}
    - q2-types >={{ q2_types }}
    - q2cli >={{ q2cli }}

test:
  requires:
    - parameterized
  imports:
    - q2_amrfinderplus
    - qiime2.plugins.amrfinderplus
  commands:
    - pytest --pyargs q2_amrfinderplus

about:
  home: https://github.com/bokulich-lab/q2-q2_amrfinderplus
  license: BSD-3-Clause
  license_family: BSD
